<?php

namespace ContainerFxx6L5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Doctrine_Orm_FailTolerantProxyCacheWarmerService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.doctrine.orm.fail_tolerant_proxy_cache_warmer' shared service.
     *
     * @return \Contao\CoreBundle\Doctrine\ORM\FailTolerantProxyCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php';

        return $container->privates['contao.doctrine.orm.fail_tolerant_proxy_cache_warmer'] = new \Contao\CoreBundle\Doctrine\ORM\FailTolerantProxyCacheWarmer(($container->privates['contao.doctrine.orm.fail_tolerant_proxy_cache_warmer.inner'] ?? $container->load('getContao_Doctrine_Orm_FailTolerantProxyCacheWarmer_InnerService')), ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));
    }
}
